# -*- coding: utf-8 -*-
"""9.a. Libraries and Modules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-_Th-sXaE6V3wwT7M3oJ4MTfoTVieDu

# Libraries or Modules

Libraries are pre defined code

Using libraries we can use the functions or method which are not in build


We use modules to break down large programs into small manageable and organized files. Furthermore, modules provide reusability of code.
"""

# Example of Libraries

import math
import time

math.pi

pi

"""We use import keyword to use libraries

Syntax

import moduleName  or


import PackageName
"""

import math

math.pi



import time

time.tzname

time.time()

# time is library
# time is function

print("sleep for ten seconds")
time.sleep(10) # it will stop execution for ten seconds
print("wake up")

import math

math.pi

import datetime

x = datetime.datetime.now()
print(x)

import datetime

x = datetime.datetime.now()

print(x.year)

import datetime

x = datetime.datetime(2020, 5, 17)

## yy mmm dd - ymd

print(x)

import math

#min() and max() are inbuild function to find the min and max value

import math

x = math.sqrt(64)

print(x)

import math


x = math.ceil(1.4)
y = math.floor(1.4)

print(x) # returns 2
print(y) # returns 1

import math

math.sqrt(36)

"""you can create an alias when you import a module, by using the as keyword:"""

import pandas

# pandas.read_CSV(" Path ")

import numpy as np

import pandas as pd

#pd.read_CSV("path")

import sklearn.preprocessing

sklearn.preprocessing.binarize

import sklearn.preprocessing as sp

sp.binarize

"""Syntax

packages are collection of module

import packagename.libraryname

from packagename import library Name
"""

# without using Alias Keyword
# we can use from keyword to import modules without using alias

from sklearn.preprocessing import binarize

# If we user * we will import all function in that module

from time import *

"""To install external Library

"""

import pytroch

import keras

# we dont have module here in pytroch so we have to install that module in pythin
# we pip keyword to install the module

"""# PIP

PIP is a package manager for Python packages, or modules

syntax

pip install modulename

Open the command prompt ( anaconda prompt ) then run this code to install the module

Some examples to install external Module

1) pip install pytroch

2) pip install keras

3) pip insall tensorflow
"""

