# -*- coding: utf-8 -*-
"""1 Basics of Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDWnBlhx-Yugt6mzn0OvrCSU3_OGYXoi

Data Types
a) Integer
b) String
c) Boolean
"""

type(10)

type("hello")

type(True)

"""VARIABLES

A variable is a location in memory used to store some data (value).
when Assigning a variable we dont need mention the Data Type.
"""

a = 10

b = 10

c = a + b

c

"""we are using (=) to Assign the values to a variable
we can assing int , string and boolen to variables
"""

a = "hello"
b =  10
c = True
d = "welcome to Data Science"

print(a)
print(b)
print(c)
d

type(d)

"""Printing
we can have print the output in different ways

"""

# use the variable name to print the output
a

# use the print command also print the output
print(a)

# Anything which can be writtein in double string will be printed

print("Welcome to Data Science")

# we user \n to pring the value in new line
print("Welcome to Data \n Science")

"""# NUMBERS

Types in Numbers category

    Integers
    floating point numbers

    
They are defined as
int for Integers
float for floating point numbers



We can use the type() function to know which class a variable or a value belongs to and the isinstance() function to check if an object belongs to a particular class.

a= 10
"""

a=10

type(a)

b = 10.2

type(b)

import random

print(random.randrange(1, 10))

random.

import pandas as pd

import seaborn as sns

"""# BOOLEAN

boolean represent the values of True and False
"""

a = True

type(a)

"""# Strings"""

s = "hello"

s
#print(s)

s[0]

s[1]

# Indexing start with 0 and will take the values before one value of Upper Limit
# [0:3] --- 0 ,1 ,2 ( or consider N is upper limit then it will consider the values of n-1 )
s[0:3]

# Negative indexing - last elements starts with -1

s[-1]

# size of the string is 5 if we are giving the size more than string size then we will get an error of out of Range
s[8]



"""# String Slicing

You can return a range of characters by using the slice syntax.

Specify the start index and the end index, separated by a colon, to return a part of the string.

"""

b = "Hello Every one!"
print(b[2:5])

b[-8:-1]

"""String Concatenation

"""

a = "Hello"
b = "World"
c = a + b

c

c = a + " " + b

c



"""# Casting

Casting is process to specify a type on to variable

casing in python used as mention below

int()

float()

str()
"""

x = int(10)
y = float(12.2)
z = str("hello")

type(z)
#y
#z

# See Some print statements

print("hello world")

x = 'Datascience'

print ("welcome to",x)

x = 2
x
y = 2
y
print("value of x :",x)
z=  x + y
x
z
print("sum of x and y is :",z)
x
y
z

