# -*- coding: utf-8 -*-
"""2 Basic of Python - Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOg4kP94Fl1-dGFVcBzK8AdiQSlCT2mM

Functions
"""

a = "welcome"

a.capitalize()

# Dot and tab will provide you the list of functions. We can use them directly

b = "money"

b

# It will comvert first letter of word into Captial
b = b.capitalize()

b

# it will convert word in lower case letter
b = b.lower()

b

# It will convert all letters in Captial

b = b.upper()

b

# to Find the index of letter in word
b.find("N")

# To check Upper case data is upper case or not
b.isupper()

# to Check Data is lower case or not
b.islower()

f="Hello World"

# number of times repeating
f.count("l")

# replace the existing letters with new letters

f=f.replace("o","k")#old letter,new letter

f

c = " welcome to Data science"

c.split()

a = " Hello world  "

# Strip method remove the white space from the string
a.strip()

age = 36
test = "My name is John, and I am {}"

test

test.format(age)

