# -*- coding: utf-8 -*-
"""3 List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjXSQS-1f7vesN4a0J649iQhT1Q-WLum

List

1) List is collection of elements
2) Purpose of list is to group up the things which fall under same category
3) List is one of the Data Structure
4) list is enclosed in []
5) lists are mutable , we can change the values in lists
"""

a = [2,3,4,5,6]

type(a)

#we can also create the list with different data structure

b =[2,3,"hello","welcome",True, False]
b

# In list indexing remain same it start with 0

b[0]

b[2:4]

b[2:]

b[-1]

# Find the lenght of List
len(a)

# changing the value in list

a =[2,3,4,5,6]
a

a[2] = 10

a

# LIST APPEND : Add an item to end of the list

a =[2,3,4,5,6]

a.append(10)

a

# INSERT : Add an item in specified Index

a =  [2,3,4,5,6]

a.insert(1,15)

a

# Remove : Remove item from list based on value

b =[2,3,"hello","welcome",True, False]
b

b.remove("welcome")

b

# del : Remove the specified Index
b =[2,3,"hello","welcome",True, False]

del b[4]

b

# pop() : removes the specified index, (or the last item if index is not specified):
b =[2,3,"hello","welcome",True, False]

b.pop()

b

# Del can also delete the list completly

b =[2,3,"hello","welcome",True, False]

del b

b

# Clear method will clear the items in the list

b =[2,3,"hello","welcome",True, False]

b.clear()

b
# its empty List

# list willl also accept Duplicate values

x =[2,3,4,5,5,5,6,6,7]

x

# want to check the count of one item

x.count(5)

b =[2,3,"hello","welcome",True, False]

# To reverse the list
b.reverse()

b

a = [2,9,3,8,4,7]

a.sort()

# it will convert into Ascending Sort
a

# To convert in desccending order
a.sort(reverse= True)

a

# list inside list
new_list = [1,2,[3,4,5],6,7] # We have a list inside a list, we have index and list inside will be one index not seperate

new_list[1]

x = new_list[2] # it gives the inside list a one index
x

new_list[2][1] # In that small list which is inside i want first element

new_list[2][0:2]

# Addinng items to List
list =[1,2,3]

list1 = list + [29,30,31]

list1

# Extend function

list =[1,2,3]

b = [4,5,6]

list.extend(b)

list

