# -*- coding: utf-8 -*-
"""4. Tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EydGdpj6oxLdNbyo_fyEFFaptrahnJv

Tuples

A tuple is Similiar to List

The diffence diffence between the two is that we can't change the elements of tuple we can't change the elements of tuple once it is assigned whereas in the list, elements can be changed

Tuple is immutable

Tuples use parentheses parentheses, whereas lists use square brackets.
"""

t1 = (1,2,"hello",True)

t1

# Access Tuple Items with Index Numbering
t1[1]

# Negative Indexing refers the index from last item

t1[-1]

# Range of Indexes

t1[1:4]

# Range of Negative Index
t1[-4:-1]

# length of Tuple

len(t1)

# To Add items
t1 = (1,2,"hello",True)

t1

t1[3] = False

# To remove the Tuple
del t1

# Joining twot Tuples
t1 = (1,2,"hello",True)
t2 =(False,"world")

t3 = t1+t2

t3

# Count - Number of times a word is getting repeated

t3.count(2)

# to find the index number of Item in the tuple

t3.index("hello")

# tuple with one value end with Comma

t4 = (2,)

t4

# Nested Tuple
# create a tuple with one value and one tuple and one list

t5 = (1, (2, 3, 4), [1, "hello","world", 28, 'abc'])

t5

# Repeat the elements in a tuple for a given number of times using the * operator.
t6 = (("hello",)* 4)

t6

# Tuple Sort
t7 = (3,2,1,4,6,5)

t8 = sorted(t7)

t8

# Largest Elements
max(t8)

# Smallest Elements
min(t8)

# using tuple we can create for loops
t =(1,2,3,4,5)
print('tuple')
for x in t:
    print(x)

