# -*- coding: utf-8 -*-
"""5.Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsJphoqMCIwHYWRuZ9_iI2Yp3z4iGORV

Dictionary

Python dictionary is an unordered collection of items

data types have only value as an element, a dictionary has a key: value pair
"""

alien = {'color':'green','points':5}

alien

alien['color'] # mba['workex']

# if the key is not available it wil gives Error
alien['name']

# Another way of Accessing Key
print(alien.get('points'))

dict = {'name':'krish','age':25,'color':'green','points':5}

dict

# Update Dict

dict['color'] = 'yellow'

dict

# Remove the element with value
dict.pop('age')

dict

dict = {'name':'krish','age':25,'color':'green','points':5}

# To remove all the values

dict.clear()

dict

dict = {'name':'krish','age':25,'color':'green','points':5}

# To Remove the dictonary itself

del dict

dict

dict = {'name':'krish','age':25,'color':'green','points':5}

# Length of the dictionary

len(dict)

dict = {'name':'krish','age':25,'color':'green','points':5}

# To Add the items to existing dictionary
dict['salary']= 50000

dict

# TO copy the Dictionary

dict = {'name':'krish','age':25,'color':'green','points':5}

dup = dict.copy()

dup

# Nested Dictionary

Ndict = {
  "Rohan" : {
    "name" : "rohan@gmail.com",
    "year" : 2004
  },
  "kumar" : {
    "name" : "kumar@gmail.com",
    "year" : 2007
  },
  "krish" : {
    "name" : "krish@gmail.com",
    "year" : 2011
  }
}

Ndict

