# -*- coding: utf-8 -*-
"""6 Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMmkvbKKoaR6juhEUGeD-I3jddKwTH_j

# SETS

A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets.
"""

s ={12,13,14,15}

s

# In Set we cannnot access by an index number  but we can use them using for Loop

s ={12,13,14,15}
for x in s:
    print(x)

# To change the items : add()
s

s.add(16)

s

# To add more than item we have to use Udpate()

s.update([17,18])

s

# length of set

len(s)

# To Remove the item
s.remove(12)

s

s.discard(13)

s

s ={12,13,14,15}

s.clear()

s

# To add two sets

s1 ={12,13,14,15}
s2={16,17,18}

s4 = s1 + s2

s3 = s1.union(s2)

s3

s ={12,13,14,15}

s.discard(14)

s

# Set doesn't allow duplicates. They store only one instance.
s = {1, 2, 3, 1, 4}
s

# Add multiple elements
s.update([5, 6, 1])
s

