# -*- coding: utf-8 -*-
"""8  Control Structures .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ayGRAzBjGW7gocZMuUoUXCRlz0uVR_Kd

Control structures are used to control the flow of execution.
"""

#An "if statement" is written by using the if keyword.

a = 10
b = 20
if b > a:
  print("b is greater than a")

## If statement
x = 3
if x < 5: # condtion value is True then loop will excute
    print ("x is less than 5")

"""# If...Else Statement"""

#When we want to execute two blocks of code exclusively we use if-else statement.

x = 12
if x < 5:
    print ("x is less than 5")
else:
     print("x is greater than 5")

num = 2
if num > 0:
    print("Positive number")
else:
    print("Negative Number")

x = int(input("Enter x:")) # input to give the value at the run time

if x%2 == 0:

    print("Even")
else:
    print("Odd")
print('The End')

"""# if...elif...else Statement

The if statements are executed from the top down.

As soon as one of the conditions controlling the if is true, the statement associated with that if is executed,

and the rest of the ladder is bypassed. If none of the conditions is true, then the final else statement will be executed.
"""

x = 21
if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

"""# Nested if Else Statement"""

a=12
b=13
if(a>11): # boolean is False #1
    print("a is 11")
    print("In if condition")
elif(a==9 and b<15): #2
    print("a is greater than 9")
    print("In elif condition")
elif(a>9 and b<15): #3
    print("a is greater than 9")
    print("In elif-2 condition")
else: #4
    print("No condition satifies")
    print("In else condition")
print("out of condition")

i = 20
if (i == 10):
    print ("i is 10")
elif (i == 15):
    print ("i is 15")
elif (i == 20):
    print ("i is 20")
else:
    print ("i is not present")

"""# Nested if Statements"""

i = 10
if (i == 10): #false
        #  First if statement
    if (i < 15):
        print ("i is smaller than 15")
    # Nested - if statement
    # Will only be executed if statement above
    # it is true
    if (i < 12):
        print ("i is smaller than 12 too")
    else:
        print ("i is greater than 15")

"""# Multiple If Case statements"""

# The factors for a given numbers

x = int(input("Enter x:"))

if x%3 == 0 :
    print("3 is a factor")

if x%7 == 0 :
    print("7 is a factor")

if x%11 == 0 :
    print("11 is a factor")

print("The End")

"""# Pass Statement"""

a = 33
b = 200

if b > a:
  pass

