# -*- coding: utf-8 -*-
"""1.a Numpy Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrW_pYiBpmm3j3KbxWFDScLBtt6ZpAzq
"""

## Numpy ( numerical for Python)
# It will provide more efficent storage and Data operation as size grows
#NumPy’s main object is the homogeneous multidimensional array.
import numpy as np

a = np.arange(15)

a

a.reshape(3,5)

a.ndim

a.dtype.name

a

a.size

a[1:3]

a[4:]

a[4]

a[8]

# Reverse the order of array
a[::-2]

x = a.reshape(3,5)
x

x[2]

# two rows and three columns
x[:2, :3]

# three rows and two colums
x[:3, :2]