# -*- coding: utf-8 -*-
"""2a.Pandas - Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EnpZ3ZebyTtY0rq3FjolHNx4aK2OE42
"""

# PANDAS
# it is a python package providing fast, flexible and Expressive data structures designed
# pandas is top of numpy

# Pandas is build on two data structures 1) series 2) dataframe

# 1 ) Series : it is one dimensional labelled array capable of holding any datatype.
#Series(data,index=index)
# Series will be created in Array , Dictm , scalar value or constant

# Creating  a series from ndarray

# import the pandas library and aliasing as pd
import pandas as pd
import numpy as np

test = np.array(['s','o','c','i','a','l'])
test

s = pd.Series(test)
s

x= 2
y = 3
z = x+y
print(z)
a = z+ 2
a

test = np.array(['s','o','c','i','a','l'])

s = pd.Series(test,index = [1,2,3,4,5,6])

s

# Dict
# dictionary keys are taken in sorted order to construct index

test = {1:'a',2:'b'}

s = pd.Series(test)
s

# Scalar
# if the data have repeated value then we have to match the index ( so index value will be repeating)
x = pd.Series(2,index=[0,1,2])
x

# Series Indexing
s = pd.Series([1,2,3,4,5,6],index = ['s','o','c','i','a','l'])
s

s['a']

s['o']

s['i']



