# -*- coding: utf-8 -*-
"""3a Data Frame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKJppKm_gMiROwpjXfy_Ak6NwH6-1bni
"""

# Pandas DataFrame

# import packages
import pandas as pd
import numpy as np

test =[1,2,3,4,5]
test

df1 = pd.Series(test)
df1

df = pd.DataFrame(test)
df

## Creating a Table
table = [['srinu',25],['kishore',26],['mani',27],['ratna',28]]

table

df = pd.DataFrame(table,columns =['Name','Age'])

df

table1 = {'Name':['srinu','kishore','mani','ratna'],'Age':[25,26,27,28]}

df = pd.DataFrame(table1,index=[1,2,3,4])

df

## Columns Selection , deletion , addition
df['weight'] = pd.Series([65,75,85,90],index = [1,2,3,4])

df

df['height'] = pd.Series([150,151,152,153],index = [1,2,3,4])
df

# creating the table
table12 = {'Name':['srinu','kishore','mani','ratna','ramu'],'Age':[25,26,27,28,29],'height':[151,152,153,154,155],'weight':[65,76,78,87,88]}
table12
td = pd.DataFrame(table12,index=[1,2,3,4,5])
td

# deleting the column
del td['Age']
td
# other method to delete the column
#td.pop('two')

td

# row selection
td.iloc[3:5]
# giving the index number to select the particular Row

# multiple Selection
td[1:5]

# Addition of Rows to existing
df = pd.DataFrame([[1,2],[3,4]],columns=['a','b'])

df

df2 = pd.DataFrame([[5,6],[7,8]],columns=['a','b'])
df2

## To add rows
df = df.append(df2)
df

df = pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2 = pd.DataFrame([[5,6],[7,8]],columns=['a','b'])
df = df.append(df2)
df

td
td.head(6)

td.tail(3)

import pandas as pd

df1=pd.DataFrame(
    {"emp_id":[1,2,5,4],'Name': ["Alex","John","Abhishek","Watson"], 'Age': [25,30,24,20]})

df2=pd.DataFrame(
    {"emp_id":[1,2,3,4],'Name': ["Alex","John","Krishna","Abhishek"], 'Weight': [60,65,70,75]})

df1

df2

pd.merge(df1,df2)

pd.merge(df1,df2,how="outer")

pd.merge(df1,df2,how="outer",on=["Name"])

# it will add the based on the name columns

