# -*- coding: utf-8 -*-
"""6.Outlier Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112XlnT0HUD0KbBWYUHZSXJUbG8sFLcqa
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

mba = pd.read_csv("D:\\Course\\Python\\Datasets\\mba.csv")

mba.boxplot()

mba.boxplot(column='gmat')

# other way to draw boxplot
import seaborn as sns
sns.boxplot(mba['gmat'])

# Process to Remove Outliers

mba.describe()

#Q11 = 690
#Q33 = 730
#IQR = q3-q1
#low = q1 - 1.5 *IQR
#high = q3+1.5 *IQR

q1 = mba['gmat'].quantile(0.25)

q1

q3 = mba['gmat'].quantile(0.75)
#q3 = 730

q3

iqr = q3-q1

iqr

# Lower Boundary

low  = q1-1.5*iqr
low

# Upper Boundary

high = q3+1.5*iqr
high

mba.shape

# any value which are greater than lower boundary and less than Upper boundary are not ourliers

mba1 = mba.loc[(mba['gmat'] > low) & (mba['gmat'] < high)]

mba.shape

mba1.shape # 15 values are removed

import seaborn as sns
sns.boxplot(mba1['gmat'])

# Method 2 to Remove the outlier

out = mba[(mba['gmat'] < low) | (mba['gmat']> high)].index

out

mba2 = mba.drop(out)

mba2

mba.drop(out,inplace=True)

mba

"""# Method 3

Replace the Outlier

lower outlier is repalced with lower boundary


Upper outlier is replaced with upper boundary

"""

mba = pd.read_csv("D:\\Course\\Python\\Datasets\\mba.csv")
mba

mba[(mba['gmat'] < low)]

low  = q1-1.5*iqr
low

mba[(mba["gmat"]<low)]

out1 = mba[(mba["gmat"]<low)].values
out1

mba['gmat'].replace(out1,low,inplace=True)

mba

sns.boxplot(mba['gmat'])

"""# To replace with mean or median"""

mean = mba['gmat'].mean()

mean

mba = pd.read_csv("D:\\Course\\Python\\Datasets\\mba.csv")
mba

mba['gmat'].replace(out1,mean,inplace=True)

mba

