# -*- coding: utf-8 -*-
"""7 Data Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FOTxBvdiuyUGi_DtkZTl1mD6iNBfnz3
"""

import pandas as pd

import numpy as np

mba = pd.read_csv("D:\\Course\\Python\\Datasets\\mba.csv")
mba

del mba['Datasrno']

mba

names = mba.columns
names

"""# Standardization"""

from sklearn import preprocessing

# scaler is function using to create the standard function

scaler = preprocessing.StandardScaler()

mba1 = scaler.fit(mba) # applied on the data set

mba1 = scaler.transform(mba) # it wil conver the values into scaled data

mba1

mba1 = pd.DataFrame(mba1, columns=names)

mba1

"""# Method 2 for Standardization

we can use scale function to standardize the data

Scale function is available under sklearn Module
"""

from sklearn.preprocessing import scale
mba2 = scale(mba)

mba2

mba2 = pd.DataFrame(mba2, columns=names)
mba2

"""# Normalization - ReScale the Data"""

from sklearn.preprocessing import MinMaxScaler

# scaler is function using to create the standard function

#scaler = preprocessing.StandardScaler()

scale = MinMaxScaler()

mba3 = scale.fit(mba)

mba3 = scale.transform(mba)

mba3

mba3 = pd.DataFrame(mba3, columns=names)

mba3

"""# Method 2 for Normaliztion"""

mba4 = (mba - mba.min())/ (mba.max() -  mba.min())

mba4

